# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/alquiler_vehiculos?useSSL=false&serverTimezone=UTC

<<<<<<< HEAD
#para conectar localhost
#spring.datasource.url=jdbc:mysql://localhost:3306/alquiler_vehiculos?useSSL=false&serverTimezone=UTC

#para conectar con localhost
#spring.datasource.url=jdbc:mysql://localhost:3306/alquiler_vehiculos?useSSL=false&serverTimezone=UTC

>>>>>>> 51320f2cfe376663635ab0b2ec5b46c8e0aaffa4
spring.datasource.username=root
spring.datasource.password=pepe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# Configuración para recursos estáticos
spring.resources.static-locations=classpath:/static/



